### ISSUE TITLE
adopt skill.json for examples

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/skill-ovos-homescreen#104]
skill.json files are now part of the locale folder of skills and have language support

https://openvoiceos.github.io/ovos-technical-manual/skill_json/

osm should be dropped and those files uses instead https://github.com/OpenVoiceOS/skill-ovos-homescreen/blob/dev/__init__.py#L211-L226

probably should introduce a new bus api to handle the skill.json files

**Comment by NeonDaniel** [comment]
This could be delegated to the `SkillManager` since it already manages what skills/intents are loaded (including which languages). This could also be left to another skill to provide the examples via the SkillAPI which was the original implementation here and what Neon does to allow for formatting the examples

**Comment by JarbasAl** [comment]
yes, a request/response from skill manager should be consumed by this skill

but workshop base skill class should register these files via bus like it does for intents, to account for standalone skills

**Comment by JarbasAl** [comment]
duplicated... #128
